version: "3"

services:

  psp:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres

  db:
    image: postgres:12-alpine
